### ISSUE TITLE
Compile 

### ISSUE THREAD

**Issue by SimplyHate** [funkemunky/Daedalus#4]
Idk how to compile a resource can someone help?

**Comment by RexyTheDev** [comment]
Uhhhh. Its Easy. Its called youtube.

**Comment by SimplyHate** [comment]
Well the YouTube videos that I find are not working

**Comment by SimplyHate** [comment]
Can you send a YouTube link for compiling plugins?

**Comment by ridalarry** [comment]
Install Eclipse
Install GitHub Desktop
on the main page of the plugin click on the green button for cloning or downloading
choose open with github desktop 
now open eclipse and create a new project
unchek the option for using the default directory
click browse
go to documents/GitHub
open Daedalus
then select it
if it have issues in compiling like errors in all of the classes
right click on the project name select java build path 
libraries
external jar
add spigot and protocollib
it should work on most of the versions on compiling except 1.13 mostlikely
if you have an error related to in getlogcommand class
in the imports you will find this line "import net.minecraft.util.org.apache.commons.io.FileUtils;"
make it this instead "import org.apache.commons.io.FileUtils;"

**Comment by SimplyHate** [comment]
Thanks!
